Repository School-of-Company/Gwangsan-Crossplatform, pull requests merged in 2025-07, with the labels that each got.

#4 온보딩 페이지를 제작
  App.tsx
  src/app/onboarding/page.tsx
  src/entity/.gitkeep
  src/entity/onboarding/index.ts
  src/entity/onboarding/ui/AuthButtonContainer/index.tsx
  src/entity/onboarding/ui/SlideIndicator/index.tsx
  src/shared/assets/png/images.d.ts
  src/shared/assets/png/onboardingSlide1.png
  src/shared/assets/png/onboardingSlide2.png
  src/shared/assets/png/onboardingSlide3.png
  src/shared/types/RootStackParamList.ts
  src/view/onboarding/index.ts
  src/view/onboarding/ui/OnboardingPage/index.tsx
  src/widget/.gitkeep
  src/widget/onboarding/index.ts
  src/widget/onboarding/ui/OnboardingSlideViewer/index.tsx
Labels: 🎨 Type: Publishing

#6 feat: main page 퍼블리싱
  babel.config.js
  package-lock.json
  package.json
  src/app/_layout.tsx
  src/app/index.tsx
  src/app/main.tsx
  src/entity/main/ui/header/index.tsx
  src/shared/assets/fonts/Cafe24Ssurround-v2.0/Cafe24Ssurround-v2.0.otf
  src/shared/assets/fonts/Cafe24Ssurround-v2.0/Cafe24Ssurround-v2.0.ttf
  src/shared/assets/fonts/Cafe24Ssurround-v2.0/License-Ssurround.pdf
  src/shared/assets/fonts/Cafe24Ssurround-v2.0/webfont/Cafe24Ssurround-v2.0.woff
  src/shared/assets/fonts/Cafe24Ssurround-v2.0/webfont/Cafe24Ssurround-v2.0.woff2
  src/shared/assets/fonts/fontLoader.tsx
  src/shared/assets/png/logo.png
  src/shared/assets/png/mainSlides/slide1.png
  src/shared/assets/png/mainSlides/slide2.png
  src/shared/assets/png/mainSlides/slide3.png
  src/shared/assets/png/mainSlides/slide4.png
  src/shared/assets/png/mainSlides/slide5.png
  src/shared/assets/png/mainSlides/slide6.png
  src/shared/types/react-native-vector-icons.d.ts
  src/shared/ui/Footer/index.tsx
  src/view/main/ui/MainPage/index.tsx
  src/widget/main/index.ts
  src/widget/main/ui/Inform/index.tsx
  src/widget/main/ui/MainSlideViewer/index.tsx
  tailwind.config.js
Labels: 2️⃣ Priority: Medium, 🎨 Type: Publishing

#10 style: 게시글 생성 페이지 제작
  package-lock.json
  package.json
  src/app/need.tsx
  src/app/offer.tsx
  src/app/request.tsx
  src/app/sell.tsx
  src/entity/product/itemForm/index.ts
  src/entity/product/itemForm/model/itemFormSchema.ts
  src/entity/product/itemForm/ui/ImageUploader/index.tsx
  src/entity/product/itemForm/ui/ItemFormProgressBar/index.tsx
  src/entity/product/itemForm/ui/LastStepButton/index.tsx
  src/entity/product/itemForm/ui/NextButton/index.tsx
  src/shared/ui/Header/index.tsx
  src/shared/ui/TextField/index.tsx
  src/shared/ui/index.ts
  src/view/product/itemForm/index.ts
  src/view/product/itemForm/ui/ItemFormPage/index.tsx
  src/widget/product/itemForm/index.ts
  src/widget/product/itemForm/ui/ItemFormConfirm/index.tsx
  src/widget/product/itemForm/ui/ItemFormContents/index.tsx
  src/widget/product/itemForm/ui/ItemFormGwangsan/index.tsx
  src/widget/product/itemForm/ui/ItemFormRenderButton/index.tsx
  src/widget/product/itemForm/ui/ItemFormRenderContent/index.tsx
Labels: 🎨 Type: Publishing

#8 feat: 프로필 퍼블리싱
  src/app/_layout.tsx
  src/app/posts.tsx
  src/app/profile.tsx
  src/entity/profile/ui/ Light/ index.tsx
  src/entity/profile/ui/Gwangsan/index.tsx
  src/entity/profile/ui/Information/index.tsx
  src/entity/profile/ui/ReviewPost/index.tsx
  src/shared/assets/png/Gwangsan.png
  src/shared/assets/png/defaultProfile.png
  src/shared/ui/Dropdown/index.tsx
  src/shared/ui/Footer/index.tsx
  src/shared/ui/Header/index.tsx
  src/shared/ui/Post/index.tsx
  src/view/main/ui/MainPage/index.tsx
  src/view/posts/ui/PostsPage/index.tsx
  src/view/profile/ui/ProfilePage/index.tsx
  src/widget/main/ui/Inform/index.tsx
  src/widget/post/ui/PostList/index.tsx
  src/widget/profile/ui/Active/index.tsx
  src/widget/profile/ui/reviewList/index.tsx
  tailwind.config.js
Labels: 2️⃣ Priority: Medium, 🎨 Type: Publishing

#12 Feat: 공지 페이지 퍼블리싱
  src/app/notice/[id]/index.tsx
  src/app/notice/index.tsx
  src/entity/notice/model/noticeData.ts
  src/entity/onboarding/index.ts
  src/shared/ui/Header/index.tsx
  src/shared/ui/SlideIndicator/index.tsx
  src/shared/ui/index.ts
  src/view/notice/index.ts
  src/view/notice/ui/NoticeDetailPage/index.tsx
  src/view/notice/ui/NoticePage/index.tsx
  src/widget/notice/index.ts
  src/widget/notice/mock/noticeDataMock.ts
  src/widget/notice/ui/NoticeDetailSlideViewer/index.tsx
  src/widget/notice/ui/NoticeItem/index.tsx
  src/widget/onboarding/ui/OnboardingSlideViewer/index.tsx
Labels: 🎨 Type: Publishing

#11 feat: 게시글 상세 페이지와 게시글 목록 페이지 퍼블리싱
  src/app/post/[id].tsx
  src/app/transaction.tsx
  src/entity/post/ui/miniProfile/index.tsx
  src/shared/ui/Button/index.tsx
  src/view/post/ui/PostPage/index.tsx
  src/view/transaction/ui/TransactionPage/index.tsx
Labels: 🎨 Type: Publishing

#14 fix: layout
  src/shared/ui/Button/index.tsx
  src/shared/ui/Header/index.tsx
  src/view/post/ui/PostPage/index.tsx
  src/view/transaction/ui/TransactionPage/index.tsx
Labels: 🎨 Type: Publishing

#19 iterm fom 페이지 ui 깨짐 문제 해결
  src/entity/signin/ui/SigninForm/index.tsx
  src/entity/signup/ui/SignupForm/index.tsx
  src/shared/ui/Header/index.tsx
  src/view/editProfile/ui/editProfilePage/index.tsx
  src/view/main/ui/MainPage/index.tsx
  src/view/notice/ui/NoticeDetailPage/index.tsx
  src/view/notice/ui/NoticePage/index.tsx
  src/view/post/ui/PostPage/index.tsx
  src/view/posts/ui/PostsPage/index.tsx
  src/view/product/itemForm/ui/ItemFormPage/index.tsx
  src/view/profile/ui/ProfilePage/index.tsx
  src/view/transaction/ui/TransactionPage/index.tsx
Labels: 🎨 Type: Publishing

#22 feat: 프로필 기능 개발
  package-lock.json
  package.json
  src/app/test/report.tsx
  src/app/test/reviews.tsx
  src/entity/auth/api/signin.ts
  src/entity/post/ui/ReportModal/index.tsx
  src/entity/post/ui/ReviewsModal/index.tsx
  src/entity/post/ui/index.ts
  src/entity/profile/ui/ Light/ index.tsx
  src/entity/profile/ui/Gwangsan/index.tsx
  src/entity/profile/ui/Information/index.tsx
  src/entity/profile/ui/Light/index.tsx
  src/entity/profile/ui/ReviewPost/index.tsx
  src/entity/profile/ui/index.ts
  src/entity/reviews/index.ts
  src/entity/reviews/ui/ReviewPost/index.tsx
  src/entity/reviews/ui/index.ts
  src/shared/consts/dong.ts
  src/shared/consts/place.ts
  src/shared/lib/axios.ts
  src/shared/lib/handleLightColor.ts
  src/view/profile/api/getMyPosts.ts
  src/view/profile/api/getMyProfile.ts
  src/view/profile/model/profileType.ts
  src/view/profile/model/useGetMyPosts.ts
  src/view/profile/model/useGetMyProfile.ts
  src/view/profile/ui/ProfilePage/index.tsx
  src/view/reviews/ui/PostsPage/index.tsx
  src/widget/profile/ui/Active/index.tsx
  src/widget/profile/ui/Introduce/index.tsx
  src/widget/profile/ui/index.ts
  src/widget/profile/ui/reviewList/index.tsx
  src/widget/signin/ui/PasswordStep/index.tsx
  src/widget/signup/ui/PlaceStep/index.tsx
Labels: ✨ Feature

#23 feat: 거래글 생성 API 연결
  src/app/post/[id]/index.tsx
  src/app/post/index.tsx
  src/entity/post/api/getItem.ts
  src/entity/post/api/report.ts
  src/entity/post/index.ts
  src/entity/post/model/reportType.ts
  src/entity/post/model/useGetItem.ts
  src/entity/post/ui/ReportModal/index.tsx
  src/entity/post/ui/miniProfile/index.tsx
  src/entity/product/itemForm/api/createItem.ts
  src/entity/product/itemForm/index.ts
  src/entity/product/itemForm/model/itemFormSchema.ts
  src/entity/product/itemForm/model/useCreateItem.ts
  src/entity/product/itemForm/ui/ImageUploader/index.tsx
  src/entity/product/itemForm/ui/LastStepButton/index.tsx
  src/shared/api/uploadImage.ts
  src/shared/model/useUploadImage.ts
  src/shared/ui/Header/index.tsx
  src/shared/ui/Post/index.tsx
  src/view/post/ui/PostPage/index.tsx
  src/view/product/itemForm/ui/ItemFormPage/index.tsx
  src/view/transaction/ui/TransactionPage/index.tsx
  src/widget/main/ui/Inform/index.tsx
  src/widget/product/itemForm/ui/ItemFormContents/index.tsx
  src/widget/product/itemForm/ui/ItemFormRenderButton/index.tsx
  src/widget/product/itemForm/ui/ItemFormRenderContent/index.tsx
Labels: ✨ Feature

#26 fix: 다른 사람의 프로필 조회
  .vscode/settings.json
  src/app/profile/[id]/index.tsx
  src/app/reviews/[id]/index.tsx
  src/entity/profile/ui/Information/index.tsx
  src/shared/types/profileType.ts
  src/shared/ui/Footer/index.tsx
  src/view/main/api/getMyInformation.ts
  src/view/main/model/useGetMyInformation.ts
  src/view/main/ui/MainPage/index.tsx
  src/view/profile/api/getMyPosts.ts
  src/view/profile/api/getPosts.ts
  src/view/profile/api/getProfile.ts
  src/view/profile/model/useGetMyPosts.ts
  src/view/profile/model/useGetMyProfile.ts
  src/view/profile/model/useGetPosts.ts
  src/view/profile/model/useGetProfile.ts
  src/view/profile/ui/ProfilePage/index.tsx
  src/view/reviews/api/getReviews.ts
  src/view/reviews/ui/PostsPage/index.tsx
  src/widget/main/ui/Inform/index.tsx
  src/widget/profile/ui/Active/index.tsx
Labels: 🐞 Bug

#44 feat: pull to refresh
  src/view/transaction/ui/TransactionPage/index.tsx
Labels: ✨ Feature

#50 fix: profile 에러
  package-lock.json
  package.json
  src/entity/profile/ui/Information/index.tsx
  src/entity/profile/ui/Light/index.tsx
  src/entity/reviews/ui/ReviewPost/index.tsx
  src/shared/lib/handleLightColor.ts
  src/view/profile/api/getMyProfile.ts
  src/view/profile/model/useGetMyProfile.ts
  src/view/profile/ui/ProfilePage/index.tsx
  src/view/transaction/ui/TransactionPage/index.tsx
  src/widget/profile/ui/Active/index.tsx
Labels: 🐞 Bug

#63 fix: 글작성 페이지 ui가 깨지는 문제
  src/app/notification/[id]/index.tsx
  src/widget/product/itemForm/ui/ItemFormConfirm/index.tsx
Labels: 🐞 Bug

#74 Fix: 신고 타입에 따라 sourceId 다르게 주게끔 수정했습니다
  src/entity/post/api/report.ts
  src/entity/post/model/useReport.ts
  src/entity/post/ui/ReportModal/index.tsx
  src/view/post/ui/PostPage/index.tsx
Labels: ♻️ Refactor, 🐞 Bug
